apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlm-scheduler
spec:
  selector:
    matchLabels:
      app: wlm-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: wlm-scheduler
    spec:
      containers:
      - name: wlm-scheduler
        image:  trilio/tvr-workloadmgr-api:4.0.9
        command: [ "/bin/sh","-c" ]
        args: [ "/home/rhv/myansible/bin/python3 /home/rhv/myansible/lib64/python3.7/site-packages/workloadmgr/mount_backup_target.py; su vdsm bash -c '/home/rhv/myansible/bin/workloadmgr-scheduler --config-file=/etc/workloadmgr/conf/workloadmgr.conf'" ]
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "150m"
            memory: "1.5Gi"
          requests:
            cpu: "90m"
            memory: "800Mi"
        volumeMounts:
        - name: tvault-config
          mountPath: /etc/tvault-config
          readOnly: false
        - name: workloadmgr-config
          mountPath: /etc/workloadmgr/conf/workloadmgr.conf
          subPath: workloadmgr.conf
        - name: vault-config
          mountPath: /etc/workloadmgr/vault.conf
          subPath: vault.conf
        - name: ceph-cert
          mountPath: /opt/stack/config-certs/
      volumes:
        - name: tvault-config
          configMap:
            name: tvault-config-file
        - name: workloadmgr-config
          configMap:
            name: workloadmgr-config-file
        - name: vault-config
          configMap:
            name: vault-config-file
        - name: ceph-cert
          configMap:
            name: ceph-cert
      imagePullSecrets:
        - name: regcred-trilio
---
apiVersion: v1
kind: Service
metadata:
  name: wlm-scheduler
spec:
  ports:
  - name: http
    port: 8780
  - name: websocket
    port: 8888
  selector:
    app: wlm-scheduler
  type: ClusterIP
